name: 3.13-main

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/build_3_13-main.yml'
      - '3.13/**'
      - 'overlay/**'
      - 'VERSION'

jobs:
  3_13-main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read Alpine version - revision
        uses: bencgreen/read-file-action@v1
        with:
          path: ./3.13/ALPINE_REVISION
        id: alpine_revision
      -
        name: Read image version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./3.13/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bcgdesign/alpine-s6:latest
            bcgdesign/alpine-s6:${{ steps.version.outputs.content }}
            bcgdesign/alpine-s6:alpine-3.13
            bcgdesign/alpine-s6:alpine-3.13-${{ steps.version.outputs.content }}
            bcgdesign/alpine-s6:alpine-${{ steps.alpine_revision.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
