name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        alpine: [ "3.15", "3.16", "3.17", "3.18", "3.19", "3.20", "3.21", "3.22" ]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read Alpine version - revision
        uses: bfren/read-file@v2
        with:
          file: ./${{ matrix.alpine }}/ALPINE_REVISION
        id: alpine_revision
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_PUBLISHING=1
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/alpine-s6:alpine${{ matrix.alpine }}
            bfren/alpine-s6:alpine${{ matrix.alpine }}-${{ steps.version_major.outputs.contents }}
            bfren/alpine-s6:alpine${{ matrix.alpine }}-${{ steps.version_minor.outputs.contents }}
            bfren/alpine-s6:alpine${{ matrix.alpine }}-${{ steps.version.outputs.contents }}
            bfren/alpine-s6:alpine${{ steps.alpine_revision.outputs.contents }}
            bfren/alpine-s6:alpine${{ steps.alpine_revision.outputs.contents }}-${{ steps.version.outputs.contents }}
            quay.io/bfren/alpine-s6:alpine${{ matrix.alpine }}
            quay.io/bfren/alpine-s6:alpine${{ matrix.alpine }}-${{ steps.version_major.outputs.contents }}
            quay.io/bfren/alpine-s6:alpine${{ matrix.alpine }}-${{ steps.version_minor.outputs.contents }}
            quay.io/bfren/alpine-s6:alpine${{ matrix.alpine }}-${{ steps.version.outputs.contents }}
            quay.io/bfren/alpine-s6:alpine${{ steps.alpine_revision.outputs.contents }}
            quay.io/bfren/alpine-s6:alpine${{ steps.alpine_revision.outputs.contents }}-${{ steps.version.outputs.contents }}
      -
        name: Build and push default tags
        id: docker_build_default
        if: matrix.alpine == '3.22'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_PUBLISHING=1
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/alpine-s6:latest
            bfren/alpine-s6:${{ steps.version_major.outputs.contents }}
            bfren/alpine-s6:${{ steps.version_minor.outputs.contents }}
            bfren/alpine-s6:${{ steps.version.outputs.contents }}
            quay.io/bfren/alpine-s6:latest
            quay.io/bfren/alpine-s6:${{ steps.version_major.outputs.contents }}
            quay.io/bfren/alpine-s6:${{ steps.version_minor.outputs.contents }}
            quay.io/bfren/alpine-s6:${{ steps.version.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
